# Parameters needed for trajectory ejecution with Motion Stack

control_plugin_frequency: 30.0 # 20-30 Hz

controlled_robot_IDs: [75] # Realman: 75

# zero_joint_positions: 
#   leg75_joint1: 0.0
#   leg75_joint2: 0.0
#   leg75_joint3: 0.0
#   leg75_joint4: 0.0
#   leg75_joint5: 0.0
#   leg75_joint6: 0.0
#   leg75_joint7: 0.0

defined_joint_states:
  - [0.0, 0.0, -3.1, 0.56, 0.0, 2.23, -3.14159]   # Start position to scan nearby
  - [0.0, 0.0, 3.1, 0.56, 0.0, 2.23, -3.14159]    # Finish position to scan nearby
  - [0.0, 0.0, 3.1, 0.0, 0.0, 2.23, -3.14159]    # Start position to scan from afar
  - [0.0, 0.0, -3.1, 0.0, 0.0, 2.23, -3.14159]     # Finish position to scan from afar

  # - [-0.1412, -1.3665, 0.0, 2.0024, 0.0, 1.5462, 0.0]   # Start position to scan from the bottom
  # - [-0.1412, -1.3665, 0.0, 2.0024, 0.0, 1.5462, 0.0]   # Finish position to scan from the bottom

n_steps: 650 # number of steps in which a target is reached  

controlled_joints: [
  "leg75_joint1", "leg75_joint2", "leg75_joint3", "leg75_joint4", "leg75_joint5", "leg75_joint6", "leg75_joint7"
]

trajectory_file: trajectory_test.csv #"scanning_traj_1.csv" # Inside /trajectories folder


